"""baseline

Revision ID: 7309a6db9fb5
Revises: 
Create Date: 2026-09-13 17:18:06.645920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7309a6db9fb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_doctor_time_slot', 'appointments', ['doctor_id', 'time_slot'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_doctor_time_slot', 'appointments', type_='unique')
    # ### end Alembic commands ###
